development:
  auth0_tenant_address: 'openware-barong.us.auth0.com'
  client_id: 've6NAufF1Pgm1jIhyQgEwa8PCG4vAoNF'
  client_secret: 'ynaE7yyYjvnuhFN_3bx435H2v0IF8jLQpwUCW8ovj-6ONRefuN7ker2L_RR5VfCI'
  redirect_uri: 'http://localhost:3000/api/v2/identity/sessions/auth0/callback'
  audience: 'https://barong.openware.service/'